"""add user profile

Revision ID: 14b70ebbfc7b
Revises: c23537e2e85e
Create Date: 2026-07-10 20:06:31.807570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '14b70ebbfc7b'
down_revision: Union[str, Sequence[str], None] = 'c23537e2e85e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.add_column('users', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'description')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
