"""init

Revision ID: c23537e2e85e
Revises: 
Create Date: 2026-05-21 20:27:45.359159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c23537e2e85e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcast_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('Spring', 'Summer', 'Fall', 'Winter', name='season_name'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'year', name='uq_broadcast_seasons_name_year'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_broadcast_seasons_slug', 'broadcast_seasons', ['slug'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('type', sa.Enum('genre', 'tag', name='category_type'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_categories_slug', 'categories', ['slug'], unique=False)
    op.create_index('ix_categories_type', 'categories', ['type'], unique=False)
    op.create_table('membership_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='plan_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('duration_days >= 0', name='ck_membership_plans_duration_non_negative'),
    sa.CheckConstraint('price >= 0', name='ck_membership_plans_price_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_membership_plans_status', 'membership_plans', ['status'], unique=False)
    op.create_table('studios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('founded', sa.Integer(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_studios_slug', 'studios', ['slug'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='user_gender'), nullable=True),
    sa.Column('role', sa.Enum('user', 'moderator', 'admin', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'email_unverified', 'suspended', 'banned', 'deleted', name='user_status'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('anime_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('title_other', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('ongoing', 'completed', 'upcoming', name='anime_status'), nullable=False),
    sa.Column('age_rating', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('access_type', sa.Enum('free', 'premium', name='content_access_type'), nullable=False),
    sa.Column('aired_from', sa.Date(), nullable=True),
    sa.Column('aired_to', sa.Date(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anime_series_access_type', 'anime_series', ['access_type'], unique=False)
    op.create_index('ix_anime_series_status', 'anime_series', ['status'], unique=False)
    op.create_index('ix_anime_series_title', 'anime_series', ['title'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('user_login', 'payment_webhook', 'membership_activated', 'moderation_action', 'admin_update', name='audit_action'), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action_created_at', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_actor_created_at', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_target', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('moderation_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moderator_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('hide_comment', 'restore_comment', 'hide_review', 'restore_review', 'ban_user', 'unban_user', 'resolve_report', 'reject_report', name='moderation_action_type'), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_moderation_actions_moderator_created_at', 'moderation_actions', ['moderator_id', 'created_at'], unique=False)
    op.create_index('ix_moderation_actions_target', 'moderation_actions', ['target_type', 'target_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('new_episode', 'reply_comment', 'membership', 'moderation', 'system', name='notification_type'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('ref_type', sa.Enum('anime', 'episode', 'comment', 'membership', 'payment', 'report', name='notification_ref_type'), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_read_created_at', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('transaction_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('gateway_event_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('payment_method', sa.Enum('momo', 'vnpay', 'stripe', 'paypal', 'bank_transfer', name='payment_method'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'refunded', name='payment_status'), nullable=False),
    sa.Column('provider_payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_payments_amount_non_negative'),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_event_id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('transaction_code')
    )
    op.create_index('ix_payments_gateway_event_id', 'payments', ['gateway_event_id'], unique=False)
    op.create_index('ix_payments_idempotency_key', 'payments', ['idempotency_key'], unique=False)
    op.create_index('ix_payments_transaction_code', 'payments', ['transaction_code'], unique=False)
    op.create_index('ix_payments_user_status_created_at', 'payments', ['user_id', 'status', 'created_at'], unique=False)
    op.create_table('user_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('accused_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('spam', 'toxic', 'harassment', 'advertising', 'other', name='userreportreason'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'reviewing', 'resolved', 'rejected', name='reportstatus'), nullable=False),
    sa.Column('admin_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('reporter_id <> accused_id', name='ck_user_reports_no_self_report'),
    sa.ForeignKeyConstraint(['accused_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_id', 'accused_id', name='uq_user_report')
    )
    op.create_index('ix_user_reports_accused_id', 'user_reports', ['accused_id'], unique=False)
    op.create_index('ix_user_reports_status_created_at', 'user_reports', ['status', 'created_at'], unique=False)
    op.create_table('anime_categories',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['anime_series.id'], ),
    sa.PrimaryKeyConstraint('series_id', 'category_id')
    )
    op.create_table('anime_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('broadcast_season_id', sa.Integer(), nullable=True),
    sa.Column('release_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('trailer_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('release_number', sa.Integer(), nullable=True),
    sa.Column('release_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('age_rating', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('status', sa.Enum('ongoing', 'completed', 'upcoming', name='anime_status'), nullable=False),
    sa.Column('access_type', sa.Enum('free', 'premium', name='content_access_type'), nullable=False),
    sa.Column('total_episodes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('release_year IS NULL OR release_year >= 1900', name='ck_anime_releases_release_year'),
    sa.ForeignKeyConstraint(['broadcast_season_id'], ['broadcast_seasons.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['anime_series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_anime_releases_access_type', 'anime_releases', ['access_type'], unique=False)
    op.create_index('ix_anime_releases_broadcast_season_id', 'anime_releases', ['broadcast_season_id'], unique=False)
    op.create_index('ix_anime_releases_series_id', 'anime_releases', ['series_id'], unique=False)
    op.create_index('ix_anime_releases_slug', 'anime_releases', ['slug'], unique=False)
    op.create_index('ix_anime_releases_status', 'anime_releases', ['status'], unique=False)
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['anime_series.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'series_id')
    )
    op.create_index('ix_favorites_series_id', 'favorites', ['series_id'], unique=False)
    op.create_index('ix_favorites_user_created_at', 'favorites', ['user_id', 'created_at'], unique=False)
    op.create_table('reviews',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('visible', 'hidden', 'pending', 'deleted', name='review_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('hidden_at', sa.DateTime(), nullable=True),
    sa.Column('moderated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('score BETWEEN 1 AND 5', name='ck_reviews_score_between_1_and_5'),
    sa.ForeignKeyConstraint(['moderated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['anime_series.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'series_id')
    )
    op.create_index('ix_reviews_series_status_created_at', 'reviews', ['series_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_reviews_user_id', 'reviews', ['user_id'], unique=False)
    op.create_table('user_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'scheduled', 'active', 'grace_period', 'expired', 'cancelled', 'refunded', name='membership_status'), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('grace_until', sa.DateTime(), nullable=True),
    sa.Column('renewed_from_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_at > start_at', name='ck_user_memberships_end_after_start'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.id'], ),
    sa.ForeignKeyConstraint(['renewed_from_id'], ['user_memberships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', name='uq_user_memberships_payment_id')
    )
    op.create_index('ix_user_memberships_payment_id', 'user_memberships', ['payment_id'], unique=False)
    op.create_index('ix_user_memberships_user_status_end_at', 'user_memberships', ['user_id', 'status', 'end_at'], unique=False)
    op.create_index('uq_user_memberships_one_active_per_user', 'user_memberships', ['user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('anime_studios',
    sa.Column('anime_release_id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_release_id'], ['anime_releases.id'], ),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ),
    sa.PrimaryKeyConstraint('anime_release_id', 'studio_id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_release_id', sa.Integer(), nullable=False),
    sa.Column('episode_num', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('video_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('release_at', sa.DateTime(), nullable=True),
    sa.Column('access_type', sa.Enum('inherit', 'free', 'premium', name='episode_access_type'), nullable=False),
    sa.Column('status', sa.Enum('processing', 'ready', 'error', name='episode_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('duration IS NULL OR duration >= 0', name='ck_episodes_duration_non_negative'),
    sa.CheckConstraint('episode_num > 0', name='ck_episodes_episode_num_positive'),
    sa.ForeignKeyConstraint(['anime_release_id'], ['anime_releases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_release_id', 'episode_num', name='uq_episodes_release_episode_num')
    )
    op.create_index('ix_episodes_access_type', 'episodes', ['access_type'], unique=False)
    op.create_index('ix_episodes_anime_release_id', 'episodes', ['anime_release_id'], unique=False)
    op.create_index('ix_episodes_release_at', 'episodes', ['release_at'], unique=False)
    op.create_index('ix_episodes_status', 'episodes', ['status'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_release_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='weekday'), nullable=False),
    sa.Column('air_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['anime_release_id'], ['anime_releases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_release_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('anime', 'episode', name='comment_target_type'), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('root_comment_id', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('reply_to_user_id', sa.Integer(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('visible', 'hidden', 'pending', 'deleted', name='comment_status'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('moderated_by', sa.Integer(), nullable=True),
    sa.Column('moderated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("((target_type = 'anime' AND series_id IS NOT NULL AND episode_id IS NULL) OR (target_type = 'episode' AND episode_id IS NOT NULL AND series_id IS NULL))", name='ck_comments_target_type_matches_target'),
    sa.CheckConstraint('((parent_comment_id IS NULL AND depth = 0) OR (parent_comment_id IS NOT NULL AND depth > 0 AND root_comment_id IS NOT NULL))', name='ck_comments_thread_shape'),
    sa.CheckConstraint('depth >= 0 AND depth <= 5', name='ck_comments_depth_limit'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['moderated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['reply_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['root_comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['anime_series.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_episode_id', 'comments', ['episode_id'], unique=False)
    op.create_index('ix_comments_parent_comment_id', 'comments', ['parent_comment_id'], unique=False)
    op.create_index('ix_comments_root_path', 'comments', ['root_comment_id', 'path'], unique=False)
    op.create_index('ix_comments_series_id', 'comments', ['series_id'], unique=False)
    op.create_index('ix_comments_status_created_at', 'comments', ['status', 'created_at'], unique=False)
    op.create_index('ix_comments_user_id', 'comments', ['user_id'], unique=False)
    op.create_table('episode_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('broken_video', 'missing_subtitle', 'wrong_subtitle', 'wrong_content', 'dead_link', 'policy_violation', 'other', name='episodereportreason'), nullable=False),
    sa.Column('playback_position_sec', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'reviewing', 'resolved', 'rejected', name='reportstatus'), nullable=False),
    sa.Column('admin_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('playback_position_sec IS NULL OR playback_position_sec >= 0', name='ck_episode_reports_playback_position_non_negative'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_episode_reports_episode_status_created_at', 'episode_reports', ['episode_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_episode_reports_reporter_created_at', 'episode_reports', ['reporter_id', 'created_at'], unique=False)
    op.create_index('ix_episode_reports_reporter_episode_created_at', 'episode_reports', ['reporter_id', 'episode_id', 'created_at'], unique=False)
    op.create_index('ix_episode_reports_status_created_at', 'episode_reports', ['status', 'created_at'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.Enum('avatar', 'cover', 'banner', 'thumbnail', 'episode_thumbnail', name='media_purpose'), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', 'deleted', name='media_status'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('((CASE WHEN user_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN series_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN episode_id IS NOT NULL THEN 1 ELSE 0 END)) = 1', name='ck_media_assets_exactly_one_owner'),
    sa.CheckConstraint('height IS NULL OR height > 0', name='ck_media_assets_height_positive'),
    sa.CheckConstraint('size_bytes IS NULL OR size_bytes >= 0', name='ck_media_assets_size_non_negative'),
    sa.CheckConstraint('width IS NULL OR width > 0', name='ck_media_assets_width_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['anime_series.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_media_assets_episode_purpose', 'media_assets', ['episode_id', 'purpose', 'status'], unique=False)
    op.create_index('ix_media_assets_series_purpose', 'media_assets', ['series_id', 'purpose', 'status'], unique=False)
    op.create_index('ix_media_assets_storage_key', 'media_assets', ['storage_key'], unique=False)
    op.create_index('ix_media_assets_user_purpose', 'media_assets', ['user_id', 'purpose', 'status'], unique=False)
    op.create_table('watch_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('progress_sec', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('watched_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('progress_sec >= 0', name='ck_watch_history_progress_non_negative'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'episode_id', name='uq_watch_history_user_episode')
    )
    op.create_index('ix_watch_history_episode_id', 'watch_history', ['episode_id'], unique=False)
    op.create_index('ix_watch_history_user_watched_at', 'watch_history', ['user_id', 'watched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watch_history_user_watched_at', table_name='watch_history')
    op.drop_index('ix_watch_history_episode_id', table_name='watch_history')
    op.drop_table('watch_history')
    op.drop_index('ix_media_assets_user_purpose', table_name='media_assets')
    op.drop_index('ix_media_assets_storage_key', table_name='media_assets')
    op.drop_index('ix_media_assets_series_purpose', table_name='media_assets')
    op.drop_index('ix_media_assets_episode_purpose', table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index('ix_episode_reports_status_created_at', table_name='episode_reports')
    op.drop_index('ix_episode_reports_reporter_episode_created_at', table_name='episode_reports')
    op.drop_index('ix_episode_reports_reporter_created_at', table_name='episode_reports')
    op.drop_index('ix_episode_reports_episode_status_created_at', table_name='episode_reports')
    op.drop_table('episode_reports')
    op.drop_index('ix_comments_user_id', table_name='comments')
    op.drop_index('ix_comments_status_created_at', table_name='comments')
    op.drop_index('ix_comments_series_id', table_name='comments')
    op.drop_index('ix_comments_root_path', table_name='comments')
    op.drop_index('ix_comments_parent_comment_id', table_name='comments')
    op.drop_index('ix_comments_episode_id', table_name='comments')
    op.drop_table('comments')
    op.drop_table('schedules')
    op.drop_index('ix_episodes_status', table_name='episodes')
    op.drop_index('ix_episodes_release_at', table_name='episodes')
    op.drop_index('ix_episodes_anime_release_id', table_name='episodes')
    op.drop_index('ix_episodes_access_type', table_name='episodes')
    op.drop_table('episodes')
    op.drop_table('anime_studios')
    op.drop_index('uq_user_memberships_one_active_per_user', table_name='user_memberships', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_user_memberships_user_status_end_at', table_name='user_memberships')
    op.drop_index('ix_user_memberships_payment_id', table_name='user_memberships')
    op.drop_table('user_memberships')
    op.drop_index('ix_reviews_user_id', table_name='reviews')
    op.drop_index('ix_reviews_series_status_created_at', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_favorites_user_created_at', table_name='favorites')
    op.drop_index('ix_favorites_series_id', table_name='favorites')
    op.drop_table('favorites')
    op.drop_index('ix_anime_releases_status', table_name='anime_releases')
    op.drop_index('ix_anime_releases_slug', table_name='anime_releases')
    op.drop_index('ix_anime_releases_series_id', table_name='anime_releases')
    op.drop_index('ix_anime_releases_broadcast_season_id', table_name='anime_releases')
    op.drop_index('ix_anime_releases_access_type', table_name='anime_releases')
    op.drop_table('anime_releases')
    op.drop_table('anime_categories')
    op.drop_index('ix_user_reports_status_created_at', table_name='user_reports')
    op.drop_index('ix_user_reports_accused_id', table_name='user_reports')
    op.drop_table('user_reports')
    op.drop_index('ix_payments_user_status_created_at', table_name='payments')
    op.drop_index('ix_payments_transaction_code', table_name='payments')
    op.drop_index('ix_payments_idempotency_key', table_name='payments')
    op.drop_index('ix_payments_gateway_event_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_notifications_user_read_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_moderation_actions_target', table_name='moderation_actions')
    op.drop_index('ix_moderation_actions_moderator_created_at', table_name='moderation_actions')
    op.drop_table('moderation_actions')
    op.drop_index('ix_audit_logs_target', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_anime_series_title', table_name='anime_series')
    op.drop_index('ix_anime_series_status', table_name='anime_series')
    op.drop_index('ix_anime_series_access_type', table_name='anime_series')
    op.drop_table('anime_series')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_studios_slug', table_name='studios')
    op.drop_table('studios')
    op.drop_index('ix_membership_plans_status', table_name='membership_plans')
    op.drop_table('membership_plans')
    op.drop_index('ix_categories_type', table_name='categories')
    op.drop_index('ix_categories_slug', table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_broadcast_seasons_slug', table_name='broadcast_seasons')
    op.drop_table('broadcast_seasons')
    # ### end Alembic commands ###
